# Generated by Django 2.1.2 on 2018-12-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('postdate', models.DateField()),
                ('cwarning', models.CharField(blank=True, max_length=300, null=True)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('mediaurl', models.CharField(blank=True, max_length=2000, null=True)),
                ('storyid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'stories',
                'managed': True,
            },
        ),
    ]
