# Generated by Django 2.1.2 on 2018-12-29 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iamshakti', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'managed': False},
        ),
    ]
