# Generated by Django 2.1.2 on 2018-12-29 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iamshakti', '0002_auto_20181229_0042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={},
        ),
    ]
