# Generated by Django 2.1.2 on 2018-12-29 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iamshakti', '0004_auto_20181229_0050'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='story',
            table='stories',
        ),
    ]
