# Generated by Django 2.1.2 on 2019-01-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamshakti', '0005_auto_20181229_0051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-postdate'], 'verbose_name_plural': 'stories'},
        ),
        migrations.AddField(
            model_name='story',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
