# Generated by Django 2.1.2 on 2019-01-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamshakti', '0006_auto_20190101_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
