# Generated by Django 2.1.2 on 2019-02-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamshakti', '0007_auto_20190101_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='jtmUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
