# Generated by Django 2.1.7 on 2019-02-18 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iamshakti', '0009_auto_20190217_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jtmuser',
            options={'ordering': ['-joindate']},
        ),
    ]
