# Generated by Django 2.1.7 on 2019-02-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamshakti', '0010_auto_20190217_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jtmuser',
            name='joindate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
