# Generated by Django 2.1.7 on 2019-02-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamshakti', '0011_auto_20190217_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jtmuser',
            name='interests',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
